spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      enabled: true
      routes:
#        filters:
#          - name: Retry
#            args:
#              retries: 3
#              series:
#                - SERVER_ERROR
#              statuses:
#                - OK
#              methods:
#                - GET
#                - POST
#              exceptions:
#                - java.lang.Exception
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  application:
    name: gbs-gatewayserver
  servlet:
    multipart:
      max-file-size: 50MB
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:pwd@test.eurake1.com:7001/eureka/
  instance:
    preferIpAddress: true
    ip-address: localhost
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000

ribbon:
  ConnectTimeout: 20000
  ReadTimeout: 20000


logging.level.org.springframework.cloud.gateway.filter.factory: TRACE
debug: true
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan}[lineno:%line]    %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"