server:
  port: 7001



eureka:
  instance:
    hostname: test.eurake1.com
    instance-id: eurake1
#    lease-expiration-duration-in-seconds: 10 # 没有心跳的淘汰时间，10秒，默认90
#    lease-renewal-interval-in-seconds: 5  # 心跳间隔，默认30
  #    hostname: localhost
  client:
    #    register-with-eureka: false #不把自己注册到eureka中
    #    fetch-registry: false #不从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://admin:pwd@localhost:7001/eureka/
  server:
    enable-self-preservation: false
    #    eviction-interval-timer-in-ms: 5000 #主动失效检测间隔,配置成5秒,默认60秒
    use-read-only-response-cache: false #禁止readOnly缓存

spring:
  application:
    name: eurake
  security:
    user:
      name: admin
      password: pwd


#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG