server:
  port: 9003
spring:
  application:
    name: consumer-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: a
    username: root
    url: jdbc:mysql://localhost:3306/springcloud_db01?characterEncodeing=utf8&serverTimezone=GMT%2B8
  cloud:
    loadbalancer:
      retry:
        enabled: false

eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 10
  client:
#    register-with-eureka: false
    healthcheck:
      enabled: true
    service-url:
#      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://admin:pwd@test.eurake1.com:7001/eureka/
#    registry-fetch-interval-seconds: 5
#    initial-instance-info-replication-interval-seconds: 10

feign:
  hystrix:
    enabled: true
#  httpclient:
#    connection-timeout: 5000


hystrix:
  command:
    default:
#    FeignService#getOne(int):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      timeout:
        enabled: true
      #断路触发条件
      circuitBreaker:
        requestVolumeThreshold: 10
        sleepWindowInMilliseconds: 40000
        errorThresholdPercentage: 50
  # hystrix的线程池配置
  threadpool:
    default:
#      coreSize: 10
      coreSize: 2
      #排队的队列的最大大小
      maxQueueSize: 200
      #开始拒绝请求阙值
      queueSizeRejectionThreshold: 500

  dashboard:
    proxy-stream-allow-list: "localhost"

#Ribbon配置
PROVIDER-TICKET:
  ribbon:
    MaxAutoRetriesNextServer: 1
    ConnectionManagerTimeout: 5000
    ConnectTimeout: 5000
    ReadTimeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: '*'


