server:
  port: 9501
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liujia13142324/springcloud-config-study.git