server:
  port: 8080
spring:
  application:
    name: consumer-user2
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: a
    username: root
    url: jdbc:mysql://192.168.200.114:3306/springcloud_db01?characterEncodeing=utf8
  cloud:
    loadbalancer:
      retry:
        enabled: false

eureka:
  client:
#    register-with-eureka: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
feign:
  hystrix:
    enabled: true
#  httpclient:
#    connection-timeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


PROVIDER-TICKET:
  ribbon:
    MaxAutoRetriesNextServer: 1
#    ConnectionManagerTimeout: 5000
#    ConnectTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: '*'

